# Generated by Django 5.0.6 on 2024-05-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'permissions': [('can_create_parcel', 'Can create parcel'), ('can_view_parcel_status', 'Can view parcel status'), ('can_confirm_delivery', 'Can confirm delivery')]},
        ),
    ]
