# Generated by Django 5.0.6 on 2024-05-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_parcel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'permissions': [('can_create_parcel', 'Can create parcel'), ('can_view_parcel_status', 'Can view parcel status'), ('can_confirm_delivery', 'Can confirm delivery'), ('assign_parcel', 'Can assign parcel'), ('update_parcel_status', 'Can update parcel status')]},
        ),
    ]
