# Generated by Django 5.0.6 on 2024-05-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_parcel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryproof',
            options={'permissions': [('upload_delivery_proof', 'Can upload delivery proof')]},
        ),
    ]
