# Generated by Django 5.0.6 on 2024-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_deliveryproof_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
